### PR TITLE
Updated Prt version to 2.5.7799

### PR DESCRIPTION
**Pull request by lor11212**
JIRA: https://zrh-web.esri.com/jira/browse/CE-9513

I bumped the prt version to 2.5.7799 and checked that everything works well. It seems that no change are necessary, everything looks good on my side.

### CODE REVIEW

**Review by mistafunk — CHANGES_REQUESTED** [review]
full rebuild fails with `1>C:\dev\git\puma\PumaDependencies\PumaDependencies.vcxproj(79,5): error MSB3030: Could not copy the file "C:\dev\git\puma\deps\ce_sdk\lib\com.esri.prt.dwg.dll" because it was not found.`

com.esri.prt.dwg.dll has been extended with ifc support and renamed to com.esri.prt.oda.dll in PRT 2.5, please adapt PumaDependencies.vcxproj accordingly.

**Comment by lor11212** [comment]
> 
> 
> full rebuild fails with `1>C:\dev\git\puma\PumaDependencies\PumaDependencies.vcxproj(79,5): error MSB3030: Could not copy the file "C:\dev\git\puma\deps\ce_sdk\lib\com.esri.prt.dwg.dll" because it was not found.`
> 
> `com.esri.prt.dwg.dll` has been extended with ifc support and renamed to `com.esri.prt.oda.dll` in PRT 2.5, please adapt `PumaDependencies.vcxproj` accordingly.

Okay...weird, why doesn't it fail on my side?

**Comment by lor11212** [comment]
I renamed the file, made a clean build and retested some rpks. It should work now.

**Review by mistafunk — APPROVED** [review]
LGTM, tested with a "footprint" RPK

**Pull request merged**
